version: '0.9'

services:

  labdb:
    container_name: labdb
    image: postgres:latest
    environment:
      POSTGRES_USER: ToDoApp
      POSTGRES_PASSWORD: DistributedSystems
      POSTGRES_NAME: ToDoApp
    ports:
      - "5432:5432"
    networks:
      - LabToDo
    volumes:
      - labdb:/var/lib/postgres/data

  labbackend:
    container_name: labbackend
    image: jabowski/distributedsystemsbackend:v1
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_USER: ToDoApp
      POSTGRES_PASSWORD: DistributedSystems
    ports:
      - "8080:8080"
    depends_on:
      - labdb
    networks:
      - LabToDo

  labfrontend:
    container_name: labfrontend
    image: jabowski/distributedsystemsfrontend:v1
    ports:
      - "8090:8090"
    depends_on: 
      - labbackend
    networks:
      - LabToDo

networks:

  LabToDo:
    driver: bridge

volumes:
  
  labdb: 
  
