version: '0.9'

services:

  postgresdb:
    build: ./LabDB
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=ToDoApp
      - POSTGRES_USER=DistributedSystems
      - POSTGRES_DB=ToDoApp
      - POSTGRES_PORT=8100
    networks:
      - LabToDo

  todobackend:
    build: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgresdb
    networks:
      - todonet

  todoui:
    image: todoui:v0.1
    ports:
      - "8090:8090"
    depends_on:
      - todobackend
    networks:
      - todonet

networks:

  todonet:
    driver: bridge


