version: '0.9'

services:

  labdb:
    container_name: labdb
    image: postgres:latest
    environment:
      POSTGRES_USER: ToDoApp
      POSTGRES_PASSWORD: DistributedSystems
      POSTGRES_NAME: ToDoApp
      POSTGRES_PORT: 8100
    ports:
      - "8100:5432"
    networks:
      - LabToDo
    volumes:
      - labdb:/var/lib/postgres/data

  labbackend:
    container_name: labbackend

    build: ./LabBackEnd
    environment:
      SPRING_PROFILES_ACTIVE: dev
      BACK_END_PORT: 8090
      POSTGRES_PORT: 8100
      FRONT_END_PORT: 8080
    ports:
      - 8090:8090
    depends_on:
      - labdb
    networks:
      - LabToDo

networks:

  LabToDo:
    driver: bridge

volumes:
  
  labdb: 
  
