apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      name: todobackend
      labels:
        app: todobackend
    spec:
      containers:
      - name: todobackend
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /todos/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 1
          failureThreshold: 3  
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: POSTGRES_HOST
          value: postgresdb
        image: novatec/technologyconsulting-containerexerciseapp-todobackend:v0.1
      restartPolicy: Always
