FROM openjdk:17-jdk-alpine
RUN mkdir -p /opt/springtestcontainer
WORKDIR /opt/springtestcontainer
COPY build/libs/testv2-0.0.1-SNAPSHOT.jar /opt/springtestcontainer
CMD ["java", "-jar", "/opt/springtestcontainer/testv2-0.0.1-SNAPSHOT.jar"]
