apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: helm-{{ .Chart.Name }}
        tier: database
    spec:
      containers:
       - image: {{ .Values.image.repository | quote }}
         name: helm-{{ .Chart.Name }}
         env:
         - name: POSTGRES_USER
           valueFrom:
             secretKeyRef:
               name: db-security
               key: db.user.name
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-security
               key: db.user.password
         - name: POSTGRES_DB
           valueFrom:
             configMapKeyRef:
               name: postgres-config
               key: postgres.db.name
