version: '3.1'

services:

  postgresdb:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb
    networks:
      - todonet

  todobackend:
    image: todobackend:v0.1
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgresdb
    networks:
      - todonet

  todoui:
    image: todoui:v0.1
    ports:
      - "8090:8090"
    depends_on:
      - todobackend
    networks:
      - todonet

networks:

  todonet:
    driver: bridge


